/**
 * The menu, as tacobell.com listed it on October 8, 2026 (captures/
 * menu-capture.md records what was read): the categories in the site's
 * order, each item's name, price and calories, what each item comes with,
 * what can be added and for how much, the "make it" switches, the boxes
 * with their components and swaps, and the Build Your Own box's groups.
 * Prices are the site's defaults for its sample store and vary by location.
 *
 * The descriptions are the study's own words. Nothing of the chain's
 * photography or marketing copy is reproduced; photographs are third
 * parties' Commons photos of the real items, credited where shown.
 */
export type Tag = "vegetarian" | "spicy" | "new" | "value" | "online";
export interface Ingredient { id: string; name: string; removable?: boolean; extra?: number; cal?: number }
export interface Option { id: string; name: string; choices: { id: string; name: string; price?: number; cal?: number; note?: string }[]; default: string }
export interface Item {
  id: string; name: string; category: string; desc: string; long?: string; price: number; cal: number; tags?: Tag[];
  photo?: string; ingredients: Ingredient[]; options?: Option[]; addons?: Ingredient[]; sauces?: Ingredient[]; url?: string;
}
export interface Category { id: string; name: string; blurb: string; url: string; show?: number }

const TB = "https://www.tacobell.com/food";
export const CATEGORIES: Category[] = [
  { id: "best-sellers", name: "Best sellers", blurb: "The thirteen the site lists first as its most popular: the Crunchwrap, the Chalupa, the tacos, the Beefy 5-Layer, Nachos BellGrande and the twists.", url: `${TB}/best-sellers`, show: 7 },
  { id: "luxe-value", name: "Luxe Value Menu", blurb: "Eleven things at $3 or less, from a $1.39 Cheesy Roll Up to a $2.99 Cheesy Double Beef Burrito.", url: `${TB}/luxe-value-menu`, show: 7 },
  { id: "cantina", name: "Cantina Chicken Menu", blurb: "Slow-roasted, marinated chicken in a bowl, a burrito, a rolled quesadilla and two tacos, with avocado verde salsa.", url: `${TB}/cantina-chicken-menu`, show: 5 },
  { id: "boxes", name: "Boxes & combos", blurb: "A main, a side and a drink in one price: the Luxe Boxes at $5, $7 and $9, the Build Your Own at $7.69, and combos from $8.99.", url: `${TB}/boxes-and-combos`, show: 6 },
  { id: "tacos", name: "Tacos", blurb: "Soft or crunchy, plain or Supreme, with the Nacho Cheese Doritos shell as the third way.", url: `${TB}/tacos`, show: 7 },
  { id: "burritos", name: "Burritos", blurb: "From a $1.99 Bean Burrito to the Grilled Cheese Burrito; the Beefy 5-Layer is the one most boxes are built on.", url: `${TB}/burritos`, show: 7 },
  { id: "specialties", name: "Specialties", blurb: "The items that exist only here: the Crunchwrap Supreme, the Chalupa Supreme, the Mexican Pizza, the Gordita Crunch and the Nacho Fries.", url: `${TB}/specialties`, show: 7 },
  { id: "quesadillas", name: "Quesadillas", blurb: "Chicken, steak or cheese, with creamy jalapeño sauce, grilled and cut in four.", url: `${TB}/quesadillas`, show: 3 },
  { id: "nachos", name: "Nachos", blurb: "Chips with nacho cheese, with guacamole, or built up into Nachos BellGrande.", url: `${TB}/nachos`, show: 3 },
  { id: "snacks", name: "Snacks & sweets", blurb: "Sides, beans, potatoes, twists and Cinnabon Delights; sauces by the packet.", url: `${TB}/snacks-sweets`, show: 7 },
  { id: "drinks", name: "Drinks", blurb: "Thirty-six on the board: fountain drinks, Freezes, dirty sodas, agua refrescas, energy drinks, coffee.", url: `${TB}/drinks`, show: 7 },
  { id: "vegetarian", name: "Veggie Cravings", blurb: "Seventeen items certified vegetarian by the American Vegetarian Association, from the Bean Burrito to the Veggie Mexican Pizza.", url: `${TB}/vegetarian`, show: 7 },
  { id: "breakfast", name: "Breakfast", blurb: "Until 10:45 a.m.: toasted burritos, breakfast quesadillas, the Breakfast Crunchwrap, hash browns and coffee.", url: `${TB}/breakfast`, show: 7 },
];

const inc = (...names: string[]): Ingredient[] => names.map((n) => ({ id: n.toLowerCase().replace(/\W+/g, "-"), name: n, removable: true }));
const A = (name: string, extra: number, cal: number): Ingredient => ({ id: name.toLowerCase().replace(/\W+/g, "-"), name, extra, cal });
/** The add-ons the site offers on a taco, burrito or specialty, with its prices. */
export const ADDONS: Ingredient[] = [A("Onions", 0.5, 0), A("Tomatoes", 0.8, 0), A("Pico De Gallo", 0.8, 0), A("Jalapeño Peppers", 0.65, 5), A("Beans", 0.65, 60), A("Three-Cheese Blend", 0.75, 20), A("Potatoes", 0.95, 100), A("Chicken", 1.5, 45), A("Steak", 1.7, 60), A("Seasoned Fries", 0.6, 120), A("Fajita Veggies", 0.89, 40), A("Purple Cabbage", 0.6, 0), A("Black Beans", 0.45, 50), A("Seasoned Rice", 0.6, 50), A("Slow-Roasted Chicken", 1.7, 60), A("Onion and Cilantro Blend", 0.5, 5), A("Fiesta Strips", 0.5, 80)];
export const SAUCES: Ingredient[] = [A("Reduced-Fat Sour Cream", 0.9, 20), A("Guacamole", 1.15, 40), A("Red Sauce", 0.45, 10), A("Green Sauce", 0.45, 0), A("Creamy Jalapeño Sauce", 0.7, 25), A("Nacho Cheese Sauce", 1.0, 30), A("Chipotle Sauce", 0.65, 25), A("Mexican Pizza Sauce", 0.3, 10), A("Avocado Ranch Sauce", 0.65, 30), A("Spicy Ranch", 0.7, 25)];
const MAKE = (supreme: boolean, grilled: boolean): Option => ({ id: "make", name: "Make it", default: "plain", choices: [{ id: "plain", name: "As it comes" }, ...(supreme ? [{ id: "supreme", name: "Supreme", price: 0.9, cal: 0, note: "Adds sour cream and tomatoes" }] : []), { id: "fresco", name: "Fresco", cal: 0, note: "Pico de gallo in place of dairy and mayo-based sauces" }, ...(grilled ? [{ id: "grilled", name: "Grilled", cal: 0 }] : [])] });
const DRINK: Option = { id: "drink", name: "Drink", default: "baja", choices: [{ id: "baja", name: "MTN DEW Baja Blast", cal: 280 }, { id: "pepsi", name: "Pepsi", cal: 250 }, { id: "diet", name: "Diet Pepsi", cal: 0 }, { id: "zero", name: "Pepsi Zero Sugar", cal: 0 }, { id: "dew", name: "MTN DEW", cal: 280 }, { id: "starry", name: "Starry", cal: 250 }, { id: "rootbeer", name: "Mug Root Beer", cal: 240 }, { id: "lemonade", name: "Tropicana Lemonade", cal: 80 }, { id: "tea", name: "Lipton Unsweetened Iced Tea", cal: 0 }] };

export const ITEMS: Item[] = [
  // Tacos
  { id: "soft-taco", name: "Soft Taco", category: "tacos", desc: "Seasoned beef, lettuce and cheddar in a warm flour tortilla.", price: 1.99, cal: 180, photo: "soft-taco-wl", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese"), options: [MAKE(true, false)], addons: ADDONS, sauces: SAUCES, url: `${TB}/tacos/soft-taco` },
  { id: "soft-taco-supreme", name: "Soft Taco Supreme", category: "tacos", desc: "The soft taco with tomatoes and reduced-fat sour cream.", price: 2.89, cal: 200, photo: "soft-taco", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese", "Tomatoes", "Reduced-Fat Sour Cream"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "crunchy-taco", name: "Crunchy Taco", category: "tacos", desc: "Seasoned beef, lettuce and shredded cheddar in a crunchy corn shell.", long: "The taco the boxes are built on, at $1.99 and 170 calories. Make it Supreme for 90 cents (sour cream and tomatoes) or Fresco (pico de gallo instead of the dairy); add anything from onions at 50 cents to steak at $1.70.", price: 1.99, cal: 170, photo: "crunchy-taco", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese"), options: [MAKE(true, false)], addons: ADDONS, sauces: SAUCES, url: `${TB}/tacos/crunchy-taco` },
  { id: "crunchy-taco-supreme", name: "Crunchy Taco Supreme", category: "tacos", desc: "The crunchy taco with tomatoes and reduced-fat sour cream.", price: 2.89, cal: 190, photo: "crunchy-taco-supreme", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese", "Tomatoes", "Reduced-Fat Sour Cream"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "dlt", name: "Nacho Cheese Doritos Locos Tacos", category: "tacos", desc: "The crunchy taco in a Nacho Cheese Doritos shell.", price: 2.89, cal: 170, photo: "doritos-nacho", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese"), options: [MAKE(true, false)], addons: ADDONS, sauces: SAUCES },
  { id: "dlt-supreme", name: "Nacho Cheese Doritos Locos Tacos Supreme", category: "tacos", desc: "The Doritos shell taco with tomatoes and reduced-fat sour cream.", price: 3.59, cal: 190, photo: "doritos-locos", ingredients: inc("Seasoned Beef", "Lettuce", "Cheese", "Tomatoes", "Reduced-Fat Sour Cream"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "doritos-cgc", name: "Doritos Cheesy Gordita Crunch", category: "tacos", desc: "A Cheesy Gordita Crunch whose crunchy shell is Nacho Cheese Doritos.", price: 6.19, cal: 480, photo: "gordita-crunch", ingredients: inc("Seasoned Beef", "Lettuce", "Three-Cheese Blend", "Spicy Ranch"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  // Burritos
  { id: "chili-cheese-burrito", name: "Chili Cheese Burrito", category: "burritos", desc: "Chili and cheese in a flour tortilla; on the value menu.", price: 2.99, cal: 380, tags: ["value"], ingredients: inc("Chili", "Cheese"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  { id: "cheesy-double-beef", name: "Cheesy Double Beef Burrito", category: "burritos", desc: "A double portion of seasoned beef with rice, nacho cheese sauce and cheddar.", price: 2.99, cal: 560, tags: ["value"], ingredients: inc("Seasoned Beef", "Seasoned Rice", "Nacho Cheese Sauce", "Cheese"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  { id: "grilled-cheese-burrito", name: "Grilled Cheese Burrito", category: "burritos", desc: "Beef, rice, sour cream, three cheeses and fiesta strips, with cheese grilled onto the outside.", price: 5.69, cal: 690, photo: "triple-melt", ingredients: inc("Seasoned Beef", "Seasoned Rice", "Reduced-Fat Sour Cream", "Three-Cheese Blend", "Fiesta Strips", "Chipotle Sauce", "Nacho Cheese Sauce"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "bb-grilled-cheese-burrito", name: "Black Bean Grilled Cheese Burrito", category: "burritos", desc: "The Grilled Cheese Burrito with black beans in place of the beef.", price: 5.19, cal: 680, tags: ["vegetarian"], photo: "triple-melt", ingredients: inc("Black Beans", "Seasoned Rice", "Reduced-Fat Sour Cream", "Three-Cheese Blend", "Fiesta Strips", "Chipotle Sauce", "Nacho Cheese Sauce"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "bean-burrito", name: "Bean Burrito", category: "burritos", desc: "Refried beans, red sauce, onions and cheddar.", price: 1.99, cal: 360, tags: ["vegetarian", "value"], photo: "dollar-cravings", ingredients: inc("Beans", "Red Sauce", "Onions", "Cheese"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES, url: `${TB}/burritos/bean-burrito` },
  { id: "beefy-5-layer", name: "Beefy 5-Layer Burrito", category: "burritos", desc: "Seasoned beef, refried beans, reduced-fat sour cream, cheddar and nacho cheese sauce, the layers between two tortillas.", long: "The burrito inside the Classic and Supreme Luxe Boxes. $4.19 and 490 calories as it comes; the site's popular upgrades are seasoned rice, onions, red sauce and creamy jalapeño sauce.", price: 4.19, cal: 490, photo: "beefy-fritos-burrito", ingredients: inc("Seasoned Beef", "Reduced-Fat Sour Cream", "Cheese", "Beans", "Nacho Cheese Sauce"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES, url: `${TB}/burritos/beefy-5-layer-burrito` },
  { id: "burrito-supreme", name: "Burrito Supreme", category: "burritos", desc: "Beef, beans, red sauce, lettuce, tomatoes, onions, cheddar and sour cream.", price: 5.69, cal: 390, photo: "menu-items", ingredients: inc("Seasoned Beef", "Beans", "Red Sauce", "Lettuce", "Tomatoes", "Onions", "Cheese", "Reduced-Fat Sour Cream"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  // Specialties
  { id: "crunchwrap-supreme", name: "Crunchwrap Supreme", category: "specialties", desc: "Seasoned beef, nacho cheese sauce, a tostada shell, lettuce, tomatoes and sour cream, folded into a hexagon and grilled.", long: "$6.89 and 530 calories. The site's popular upgrades are jalapeños, beans, guacamole and creamy jalapeño sauce; it can be made Fresco or Grilled, and a Black Bean version is $5.99.", price: 6.89, cal: 530, photo: "crunchwrap", ingredients: inc("Seasoned Beef", "Lettuce", "Reduced-Fat Sour Cream", "Nacho Cheese Sauce", "Tomatoes"), options: [MAKE(false, true)], addons: [...ADDONS, A("Chipotle Bacon", 0.99, 0)], sauces: [...SAUCES.filter((s) => s.id !== "reduced-fat-sour-cream"), A("Pepper Jack Sauce", 0.3, 70)], url: `${TB}/specialties/crunchwrap-supreme` },
  { id: "bb-crunchwrap", name: "Black Bean Crunchwrap Supreme", category: "specialties", desc: "The Crunchwrap with black beans in place of the beef.", price: 5.99, cal: 520, tags: ["vegetarian"], photo: "crunchwrap", ingredients: inc("Black Beans", "Lettuce", "Reduced-Fat Sour Cream", "Nacho Cheese Sauce", "Tomatoes"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  { id: "chalupa-supreme", name: "Chalupa Supreme", category: "specialties", desc: "A flaky fried flatbread shell with seasoned beef, lettuce, tomatoes, a three-cheese blend and sour cream.", long: "$5.69 and 350 calories; chicken is the version in the Supreme Luxe Box. Popular upgrades: guacamole, nacho cheese sauce, chipotle sauce, onions.", price: 5.69, cal: 350, photo: "chalupa-supreme", ingredients: inc("Seasoned Beef", "Tomatoes", "Lettuce", "Reduced-Fat Sour Cream", "Three-Cheese Blend"), options: [{ id: "protein", name: "Protein", default: "beef", choices: [{ id: "beef", name: "Seasoned beef" }, { id: "chicken", name: "Chicken", cal: -20 }, { id: "steak", name: "Steak", price: 0.7, cal: 0 }] }, MAKE(false, false)], addons: ADDONS, sauces: SAUCES, url: `${TB}/specialties/chalupa-supreme` },
  { id: "bb-chalupa", name: "Black Bean Chalupa Supreme", category: "specialties", desc: "The Chalupa Supreme with black beans.", price: 5.39, cal: 340, tags: ["vegetarian"], photo: "chalupa", ingredients: inc("Black Beans", "Tomatoes", "Lettuce", "Reduced-Fat Sour Cream", "Three-Cheese Blend"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "cheesy-gordita-crunch", name: "Cheesy Gordita Crunch", category: "specialties", desc: "A crunchy taco inside a warm flatbread, joined by melted three-cheese blend, with spicy ranch.", price: 5.69, cal: 480, photo: "gordita-crunch", ingredients: inc("Seasoned Beef", "Lettuce", "Three-Cheese Blend", "Spicy Ranch"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "mexican-pizza", name: "Mexican Pizza", category: "specialties", desc: "Two crisp flour shells around beef and beans, topped with pizza sauce, three cheeses and tomatoes.", price: 5.69, cal: 530, photo: "mexican-pizza", ingredients: inc("Seasoned Beef", "Beans", "Mexican Pizza Sauce", "Three-Cheese Blend", "Tomatoes"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "veggie-mexican-pizza", name: "Veggie Mexican Pizza", category: "specialties", desc: "The Mexican Pizza with black beans in place of the beef.", price: 5.69, cal: 460, tags: ["vegetarian"], photo: "mexican-pizza", ingredients: inc("Black Beans", "Beans", "Mexican Pizza Sauce", "Three-Cheese Blend", "Tomatoes"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "gordita-duos-steak", name: "Steak Gordita Crunch Duos 2pk", category: "specialties", desc: "Two small Gordita Crunches with steak.", price: 5.49, cal: 340, tags: ["new"], photo: "gordita-crunch", ingredients: inc("Steak", "Lettuce", "Three-Cheese Blend", "Spicy Ranch"), addons: ADDONS, sauces: SAUCES },
  { id: "gordita-duos-chicken", name: "Slow-Roasted Chicken Gordita Crunch Duos 2pk", category: "specialties", desc: "Two small Gordita Crunches with slow-roasted chicken; the main in the Discovery Luxe Box.", price: 5.49, cal: 340, tags: ["new"], photo: "gordita-crunch", ingredients: inc("Slow-Roasted Chicken", "Lettuce", "Three-Cheese Blend", "Spicy Ranch"), addons: ADDONS, sauces: SAUCES },
  { id: "crunchwrap-slider", name: "Creamy Chipotle Crispy Chicken Crunchwrap Slider", category: "specialties", desc: "A small Crunchwrap with crispy chicken and creamy chipotle sauce.", price: 2.69, cal: 320, tags: ["new"], photo: "fritos-slider", ingredients: inc("Crispy Chicken", "Creamy Chipotle Sauce", "Lettuce", "Cheese"), addons: ADDONS, sauces: SAUCES },
  { id: "diablo-fries", name: "Diablo Ranch Steak Nacho Fries", category: "specialties", desc: "Nacho Fries under steak, nacho cheese and Diablo ranch.", price: 5.99, cal: 500, tags: ["spicy", "new"], photo: "nachos-bellgrande", ingredients: inc("Seasoned Fries", "Steak", "Nacho Cheese Sauce", "Diablo Ranch"), addons: ADDONS, sauces: SAUCES },
  { id: "nacho-fries", name: "Large Nacho Fries", category: "specialties", desc: "Seasoned fries with a cup of nacho cheese sauce.", price: 3.89, cal: 500, photo: "nachos-bellgrande", ingredients: inc("Seasoned Fries", "Nacho Cheese Sauce") },
  { id: "mini-taco-salad", name: "Mini Taco Salad", category: "specialties", desc: "A small taco salad; on the value menu.", price: 2.49, cal: 280, tags: ["value"], photo: "menu-items", ingredients: inc("Seasoned Beef", "Lettuce", "Tomatoes", "Cheese", "Reduced-Fat Sour Cream", "Tortilla Bowl"), addons: ADDONS, sauces: SAUCES },
  { id: "chicken-stacker", name: "Avocado Ranch Chicken Stacker", category: "specialties", desc: "Chicken, cheese and avocado ranch in a folded, grilled tortilla; on the value menu.", price: 2.99, cal: 350, tags: ["value"], photo: "cantina-soft-taco", ingredients: inc("Chicken", "Cheese", "Avocado Ranch Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "potato-griller", name: "Beefy Potato Loaded Griller", category: "specialties", desc: "Beef, potatoes, cheese and sauce in a grilled tortilla; on the value menu.", price: 2.79, cal: 480, tags: ["value"], ingredients: inc("Seasoned Beef", "Potatoes", "Cheese", "Chipotle Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "cheesy-fiesta-potatoes", name: "Cheesy Fiesta Potatoes", category: "specialties", desc: "Seasoned potatoes with nacho cheese sauce and sour cream.", price: 2.89, cal: 240, tags: ["vegetarian", "value"], photo: "dollar-cravings", ingredients: inc("Potatoes", "Nacho Cheese Sauce", "Reduced-Fat Sour Cream") },
  { id: "pintos-n-cheese", name: "Pintos N Cheese", category: "specialties", desc: "Refried beans with red sauce and cheddar.", price: 2.99, cal: 170, tags: ["vegetarian"], photo: "dollar-cravings", ingredients: inc("Beans", "Red Sauce", "Cheese") },
  // Luxe value / sides
  { id: "cheesy-roll-up", name: "Cheesy Roll Up", category: "luxe-value", desc: "Three cheeses melted in a rolled flour tortilla.", price: 1.39, cal: 170, tags: ["vegetarian", "value"], photo: "cheesy-roll-up", ingredients: inc("Three-Cheese Blend") },
  { id: "spicy-potato-soft-taco", name: "Spicy Potato Soft Taco", category: "luxe-value", desc: "Potatoes, lettuce, cheddar and chipotle sauce in a soft tortilla.", price: 1.39, cal: 240, tags: ["vegetarian", "value", "spicy"], photo: "soft-taco", ingredients: inc("Potatoes", "Lettuce", "Cheese", "Chipotle Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "cheesy-bean-rice-burrito", name: "Cheesy Bean and Rice Burrito", category: "luxe-value", desc: "Beans, rice, nacho cheese sauce and creamy jalapeño sauce.", price: 1.49, cal: 400, tags: ["vegetarian", "value"], photo: "dollar-cravings", ingredients: inc("Beans", "Seasoned Rice", "Nacho Cheese Sauce", "Creamy Jalapeño Sauce"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  { id: "chips-nacho-supreme-dip", name: "Chips and Nacho Supreme Dip", category: "luxe-value", desc: "Chips with a dip of nacho cheese, beef, sour cream and tomatoes.", price: 2.49, cal: 360, tags: ["value"], photo: "nachos-bellgrande", ingredients: inc("Tortilla Chips", "Nacho Cheese Sauce", "Seasoned Beef", "Reduced-Fat Sour Cream", "Tomatoes") },
  { id: "flatbread-melt", name: "3 Cheese Chicken Flatbread Melt", category: "luxe-value", desc: "Chicken and three cheeses in a grilled flatbread.", price: 2.39, cal: 320, tags: ["value"], photo: "cantina-soft-taco", ingredients: inc("Chicken", "Three-Cheese Blend", "Creamy Chipotle Sauce"), addons: ADDONS, sauces: SAUCES },
  // Cantina
  { id: "cantina-bowl", name: "Cantina Chicken Bowl", category: "cantina", desc: "Slow-roasted chicken, seasoned rice, black beans, avocado ranch, sour cream, lettuce, purple cabbage, pico, guacamole and cheddar, with two salsa packets.", long: "$8.39 and 575 calories with its two packets (jalapeño citrus, avocado verde); 480 for the bowl alone.", price: 8.39, cal: 575, photo: "cantina-bowl", ingredients: inc("Slow-Roasted Chicken", "Seasoned Rice", "Black Beans", "Avocado Ranch Sauce", "Reduced-Fat Sour Cream", "Lettuce", "Purple Cabbage", "Pico De Gallo", "Guacamole", "Cheese"), addons: ADDONS, sauces: SAUCES, url: `${TB}/deals-and-combos/cantina-chicken-bowl` },
  { id: "cantina-burrito", name: "Cantina Chicken Burrito", category: "cantina", desc: "The bowl's fillings in a flour tortilla.", price: 6.29, cal: 570, ingredients: inc("Slow-Roasted Chicken", "Seasoned Rice", "Black Beans", "Avocado Ranch Sauce", "Lettuce", "Purple Cabbage", "Pico De Gallo", "Cheese"), options: [MAKE(false, true)], addons: ADDONS, sauces: SAUCES },
  { id: "cantina-rolled-quesadilla", name: "Cantina Chicken Rolled Quesadilla", category: "cantina", desc: "Slow-roasted chicken and cheese rolled and grilled, with sauce for dipping.", price: 6.99, cal: 650, photo: "cheese-quesadilla", ingredients: inc("Slow-Roasted Chicken", "Three-Cheese Blend", "Creamy Chipotle Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "cantina-soft-taco", name: "Cantina Chicken Soft Taco", category: "cantina", desc: "Slow-roasted chicken with purple cabbage, pico, cheddar and avocado ranch in a soft tortilla.", price: 3.19, cal: 260, photo: "cantina-soft-taco", ingredients: inc("Slow-Roasted Chicken", "Purple Cabbage", "Pico De Gallo", "Cheese", "Avocado Ranch Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "cantina-crispy-taco", name: "Cantina Chicken Crispy Taco", category: "cantina", desc: "The Cantina taco in a crispy shell.", price: 3.19, cal: 320, photo: "street-chalupa", ingredients: inc("Slow-Roasted Chicken", "Purple Cabbage", "Pico De Gallo", "Cheese", "Avocado Ranch Sauce"), addons: ADDONS, sauces: SAUCES },
  // Quesadillas
  { id: "chicken-quesadilla", name: "Chicken Quesadilla", category: "quesadillas", desc: "Grilled chicken, three cheeses and creamy jalapeño sauce.", price: 5.89, cal: 490, photo: "chicken-quesadilla", ingredients: inc("Chicken", "Three-Cheese Blend", "Creamy Jalapeño Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "steak-quesadilla", name: "Steak Quesadilla", category: "quesadillas", desc: "Steak, three cheeses and creamy jalapeño sauce.", price: 6.39, cal: 500, photo: "quesadilla-combo", ingredients: inc("Steak", "Three-Cheese Blend", "Creamy Jalapeño Sauce"), addons: ADDONS, sauces: SAUCES },
  { id: "cheese-quesadilla", name: "Cheese Quesadilla", category: "quesadillas", desc: "Three cheeses and creamy jalapeño sauce.", price: 5.49, cal: 440, tags: ["vegetarian"], photo: "cheese-quesadilla", ingredients: inc("Three-Cheese Blend", "Creamy Jalapeño Sauce"), addons: ADDONS, sauces: SAUCES },
  // Nachos
  { id: "nachos-bellgrande", name: "Nachos BellGrande", category: "nachos", desc: "Chips with beef, beans, nacho cheese sauce, tomatoes and sour cream.", price: 6.79, cal: 730, photo: "nachos-bellgrande", ingredients: inc("Tortilla Chips", "Seasoned Beef", "Beans", "Nacho Cheese Sauce", "Tomatoes", "Reduced-Fat Sour Cream"), options: [MAKE(false, false)], addons: ADDONS, sauces: SAUCES },
  { id: "chips-guac", name: "Chips and Guacamole", category: "nachos", desc: "Chips with a side of guacamole.", price: 3.79, cal: 230, tags: ["vegetarian"], ingredients: inc("Tortilla Chips", "Guacamole") },
  { id: "chips-nacho-cheese", name: "Chips and Nacho Cheese Sauce", category: "nachos", desc: "Chips with a cup of warm nacho cheese sauce; a side in the Discovery Luxe Box.", price: 2.99, cal: 220, tags: ["vegetarian"], ingredients: inc("Tortilla Chips", "Nacho Cheese Sauce") },
  // Snacks & sweets
  { id: "cinnamon-twists", name: "Cinnamon Twists", category: "snacks", desc: "Puffed, crisp, dusted with cinnamon sugar; the side in the Classic and Supreme Luxe Boxes.", price: 1.69, cal: 170, tags: ["vegetarian"], ingredients: inc("Cinnamon Sugar") },
  { id: "cinnabon-2", name: "Cinnabon Delights 2 Pack", category: "snacks", desc: "Two warm pastry bites filled with cream cheese frosting.", price: 2.89, cal: 170, tags: ["vegetarian"], photo: "cinnabon", ingredients: inc("Cream Cheese Frosting") },
  { id: "cinnabon-12", name: "Cinnabon Delights 12 Pack", category: "snacks", desc: "Twelve of them.", price: 7.39, cal: 1010, tags: ["vegetarian"], photo: "cinnabon", ingredients: inc("Cream Cheese Frosting") },
  { id: "caramel-empanada", name: "Caramel Apple Empanada", category: "snacks", desc: "A fried pastry with caramel apple filling.", price: 2.99, cal: 290, tags: ["vegetarian"], ingredients: inc("Caramel Apple Filling") },
  { id: "black-beans-rice", name: "Black Beans and Rice", category: "snacks", desc: "A cup of each.", price: 2.99, cal: 160, tags: ["vegetarian"], ingredients: inc("Black Beans", "Seasoned Rice") },
  { id: "black-beans", name: "Black Beans", category: "snacks", desc: "A cup of slow-simmered black beans.", price: 2.59, cal: 50, tags: ["vegetarian"], ingredients: inc("Black Beans") },
  { id: "chili-side", name: "Chili", category: "snacks", desc: "A side of chili.", price: 1.0, cal: 60, ingredients: inc("Chili") },
  // Drinks (seven of thirty-six)
  { id: "baja-blast", name: "MTN DEW Baja Blast", category: "drinks", desc: "The tropical lime Mountain Dew made for this menu; large is 420 calories.", price: 3.19, cal: 420, photo: "baja-blast", ingredients: [], options: [{ id: "size", name: "Size", default: "large", choices: [{ id: "medium", name: "Medium", price: -0.4, cal: -140 }, { id: "large", name: "Large" }] }], url: `${TB}/drinks/mtn-dew-baja-blast` },
  { id: "baja-blast-freeze", name: "MTN DEW Baja Blast Freeze", category: "drinks", desc: "The same, frozen.", price: 4.19, cal: 190, photo: "baja-blast", ingredients: [], options: [{ id: "size", name: "Size", default: "large", choices: [{ id: "regular", name: "Regular", price: -0.5, cal: -40 }, { id: "large", name: "Large" }] }] },
  { id: "pepsi", name: "Pepsi", category: "drinks", desc: "Large fountain Pepsi; Diet, Zero Sugar and Cherry at the same price.", price: 3.19, cal: 380, ingredients: [], options: [{ id: "size", name: "Size", default: "large", choices: [{ id: "medium", name: "Medium", price: -0.4, cal: -130 }, { id: "large", name: "Large" }] }, { id: "kind", name: "Kind", default: "pepsi", choices: [{ id: "pepsi", name: "Pepsi" }, { id: "diet", name: "Diet Pepsi", cal: -380 }, { id: "zero", name: "Pepsi Zero Sugar", cal: -380 }, { id: "cherry", name: "Cherry Pepsi", cal: 10 }] }] },
  { id: "baja-blast-dirty", name: "MTN DEW Baja Blast dirty soda", category: "drinks", desc: "Baja Blast with cream and a flavour shot.", price: 3.29, cal: 460, tags: ["new"], photo: "baja-blast", ingredients: [] },
  { id: "agua-refresca", name: "Mango Peach Agua Refresca", category: "drinks", desc: "A fruit refresher; strawberry passionfruit and dragonfruit berry are the other two.", price: 3.89, cal: 170, ingredients: [] },
  { id: "energy", name: "Pineapple Citrus Energy", category: "drinks", desc: "A caffeinated fruit drink; strawberry tropics is the other.", price: 4.49, cal: 50, tags: ["new"], ingredients: [] },
  { id: "cinnabon-coffee", name: "Iced Cinnabon Delights Coffee", category: "drinks", desc: "Iced coffee with Cinnabon flavour; hot is the same price, plain coffee $2.19 to $2.39.", price: 2.89, cal: 160, ingredients: [] },
  // Breakfast
  { id: "breakfast-crunchwrap", name: "Breakfast Crunchwrap Bacon", category: "breakfast", desc: "Eggs, hash brown, cheese, bacon and creamy jalapeño sauce in a grilled Crunchwrap; sausage and California versions too.", price: 4.99, cal: 660, photo: "breakfast-crunchwrap", ingredients: inc("Eggs", "Hash Brown", "Cheese", "Bacon", "Creamy Jalapeño Sauce"), options: [{ id: "meat", name: "Meat", default: "bacon", choices: [{ id: "bacon", name: "Bacon" }, { id: "sausage", name: "Sausage", cal: 80 }, { id: "california", name: "California (steak, guacamole, pico)", price: 0.2, cal: -20 }] }], addons: ADDONS, sauces: SAUCES },
  { id: "grande-toasted-burrito", name: "Grande Toasted Breakfast Burrito Sausage", category: "breakfast", desc: "Eggs, potatoes, cheese and sausage, toasted; bacon and steak versions too.", price: 4.89, cal: 570, ingredients: inc("Eggs", "Potatoes", "Cheese", "Sausage", "Nacho Cheese Sauce"), options: [{ id: "meat", name: "Meat", default: "sausage", choices: [{ id: "sausage", name: "Sausage" }, { id: "bacon", name: "Bacon", cal: 0 }, { id: "steak", name: "Steak", price: 0.1, cal: -10 }] }], addons: ADDONS, sauces: SAUCES },
  { id: "cheesy-toasted-burrito", name: "Cheesy Toasted Breakfast Burrito Sausage", category: "breakfast", desc: "A smaller toasted burrito with eggs, cheese and sausage; bacon or potato versions too.", price: 2.19, cal: 350, tags: ["value"], ingredients: inc("Eggs", "Cheese", "Sausage", "Nacho Cheese Sauce"), options: [{ id: "meat", name: "Meat", default: "sausage", choices: [{ id: "sausage", name: "Sausage" }, { id: "bacon", name: "Bacon" }, { id: "potato", name: "Potato", price: -0.2, cal: -10 }] }], addons: ADDONS, sauces: SAUCES },
  { id: "breakfast-quesadilla", name: "Breakfast Quesadilla Sausage", category: "breakfast", desc: "Eggs, three cheeses, sausage and creamy jalapeño sauce in a grilled tortilla.", price: 4.49, cal: 500, photo: "cheese-quesadilla", ingredients: inc("Eggs", "Three-Cheese Blend", "Sausage", "Creamy Jalapeño Sauce"), options: [{ id: "meat", name: "Meat", default: "sausage", choices: [{ id: "sausage", name: "Sausage" }, { id: "bacon", name: "Bacon" }, { id: "steak", name: "Steak", price: 0.3 }] }], addons: ADDONS, sauces: SAUCES },
  { id: "hash-brown", name: "Hash Brown", category: "breakfast", desc: "One, crisp.", price: 1.99, cal: 170, tags: ["vegetarian"], ingredients: inc("Potatoes") },
  { id: "hot-coffee", name: "Premium Hot Coffee", category: "breakfast", desc: "Brewed coffee.", price: 2.39, cal: 0, ingredients: [] },
  { id: "orange-juice", name: "Tropicana Orange Juice", category: "breakfast", desc: "Bottled orange juice.", price: 2.29, cal: 140, ingredients: [] },
];

/** A box or combo: components, each with the site's swap list, and a drink choice. */
export interface Slot { id: string; name: string; itemId: string; swaps?: string[]; cal: number }
export interface Box { id: string; name: string; price: number; calRange: string; photo?: string; blurb: string; slots: Slot[]; drink: Option; url: string; tags?: Tag[] }
export const BOXES: Box[] = [
  { id: "classic-luxe-box", name: "Classic Luxe Box", price: 5.0, calRange: "820–1100", photo: "box", blurb: "A Beefy 5-Layer Burrito, a Crunchy Taco, Cinnamon Twists and a medium drink, for five dollars.", slots: [{ id: "main", name: "Main", itemId: "beefy-5-layer", cal: 490 }, { id: "taco", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco", "spicy-potato-soft-taco"], cal: 170 }, { id: "side", name: "Side", itemId: "cinnamon-twists", swaps: ["chips-nacho-cheese"], cal: 170 }], drink: DRINK, url: `${TB}/deals-and-combos/classic-luxe-box` },
  { id: "supreme-luxe-box", name: "Supreme Luxe Box", price: 7.0, calRange: "1150–1430", photo: "chalupa-supreme", blurb: "A Chicken Chalupa Supreme, a Beefy 5-Layer Burrito, a Crunchy Taco, Cinnamon Twists and a medium drink, for seven dollars.", slots: [{ id: "chalupa", name: "Chalupa", itemId: "chalupa-supreme", swaps: ["cheesy-gordita-crunch", "bb-chalupa"], cal: 330 }, { id: "main", name: "Burrito", itemId: "beefy-5-layer", cal: 490 }, { id: "taco", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco", "dlt"], cal: 170 }, { id: "side", name: "Side", itemId: "cinnamon-twists", swaps: ["chips-nacho-cheese", "cheesy-fiesta-potatoes"], cal: 170 }], drink: DRINK, url: `${TB}/deals-and-combos/supreme-luxe-box` },
  { id: "discovery-luxe-box", name: "Discovery Luxe Box", price: 9.0, calRange: "890–1180", photo: "discovery-box", blurb: "Two Slow-Roasted Chicken Gordita Crunch Duos, a Nacho Cheese Doritos Locos Taco, a Crunchy Taco, chips and nacho cheese, and a medium drink, for nine dollars.", slots: [{ id: "main", name: "Main", itemId: "gordita-duos-chicken", swaps: ["gordita-duos-steak"], cal: 340 }, { id: "dlt", name: "Taco", itemId: "dlt", swaps: ["crunchy-taco", "soft-taco"], cal: 170 }, { id: "taco", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco", "dlt"], cal: 170 }, { id: "side", name: "Side", itemId: "chips-nacho-cheese", swaps: ["cinnamon-twists", "cheesy-fiesta-potatoes"], cal: 220 }], drink: DRINK, url: `${TB}/deals-and-combos/discovery-luxe-box`, tags: ["new"] },
  { id: "crunchwrap-combo", name: "Crunchwrap Supreme Combo", price: 9.29, calRange: "700–1120", photo: "crunchwrap", blurb: "A Crunchwrap Supreme, a Crunchy Taco and a large drink.", slots: [{ id: "main", name: "Main", itemId: "crunchwrap-supreme", swaps: ["bb-crunchwrap"], cal: 530 }, { id: "taco", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco", "dlt"], cal: 170 }], drink: { ...DRINK, name: "Large drink" }, url: `${TB}/deals-and-combos/crunchwrap-supreme-combo` },
  { id: "3-crunchy-tacos-combo", name: "3 Crunchy or Soft Tacos Combo", price: 8.99, calRange: "500–920", photo: "crunchy-taco", blurb: "Three tacos, crunchy or soft, and a large drink.", slots: [{ id: "t1", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco"], cal: 170 }, { id: "t2", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco"], cal: 170 }, { id: "t3", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco"], cal: 170 }], drink: { ...DRINK, name: "Large drink" }, url: `${TB}/deals-and-combos/3-crunchy-or-soft-tacos-combo` },
  { id: "mexican-pizza-combo", name: "Mexican Pizza Combo", price: 11.69, calRange: "900–1320", photo: "mexican-pizza", blurb: "A Mexican Pizza, two Crunchy Tacos and a large drink.", slots: [{ id: "main", name: "Main", itemId: "mexican-pizza", swaps: ["veggie-mexican-pizza"], cal: 530 }, { id: "t1", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco"], cal: 170 }, { id: "t2", name: "Taco", itemId: "crunchy-taco", swaps: ["soft-taco"], cal: 170 }], drink: { ...DRINK, name: "Large drink" }, url: `${TB}/deals-and-combos/mexican-pizza-combo` },
];

/** Build Your Own Luxe Cravings Box: one from each group, $7.69. */
export const BUILD = {
  id: "build-your-own", name: "Build Your Own Luxe Cravings Box", price: 7.69, calRange: "670–2050", photo: "cravings-box", url: `${TB}/deals-and-combos/build-your-own-luxe-cravings-box`,
  blurb: "One specialty, one taco or burrito, one side and a medium drink, for $7.69.",
  groups: [
    { id: "main", name: "Choose your main", items: ["crunchwrap-supreme", "bb-crunchwrap", "chalupa-supreme", "bb-chalupa", "cheesy-gordita-crunch", "beefy-5-layer", "cheese-quesadilla"] },
    { id: "classic", name: "Choose your classic", items: ["crunchy-taco", "soft-taco", "spicy-potato-soft-taco", "dlt", "cheesy-bean-rice-burrito", "bean-burrito"] },
    { id: "side", name: "Choose your side", items: ["cinnamon-twists", "chips-nacho-cheese", "cheesy-fiesta-potatoes"] },
  ],
  drink: DRINK,
};

export const byId = Object.fromEntries(ITEMS.map((i) => [i.id, i])) as Record<string, Item>;
export const inCategory = (c: string) => ITEMS.filter((i) => i.category === c);
export const money = (n: number) => `$${n.toFixed(2)}`;
/** Category membership for the cross-cutting lists, in the site's order. */
export const LISTS: Record<string, string[]> = {
  "best-sellers": ["crunchwrap-supreme", "chalupa-supreme", "crunchy-taco", "soft-taco", "beefy-5-layer", "nachos-bellgrande", "cinnamon-twists", "cheesy-gordita-crunch", "cheesy-bean-rice-burrito", "chicken-quesadilla", "spicy-potato-soft-taco", "nacho-fries"],
  "luxe-value": ["cheesy-roll-up", "spicy-potato-soft-taco", "cheesy-bean-rice-burrito", "flatbread-melt", "mini-taco-salad", "chips-nacho-supreme-dip", "potato-griller", "cheesy-fiesta-potatoes", "chili-cheese-burrito", "cheesy-double-beef", "chicken-stacker"],
  vegetarian: ["bean-burrito", "cheesy-bean-rice-burrito", "bb-chalupa", "bb-crunchwrap", "veggie-mexican-pizza", "cheese-quesadilla", "cheesy-roll-up", "cheesy-fiesta-potatoes", "chips-guac", "chips-nacho-cheese", "black-beans", "black-beans-rice", "pintos-n-cheese", "cinnamon-twists", "cinnabon-2", "cinnabon-12", "bb-grilled-cheese-burrito"],
};
export const DISCLAIMER = "2,000 calories a day is used for general nutrition advice, but calorie needs vary. Prices and calories are as tacobell.com listed them for its sample store on October 8, 2026; both vary by location. A layout study; nothing here is an offer and no order is placed.";
